### ISSUE TITLE
The 2nd downloaded content within the same channel cannot be played

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#681] opened 2023-06-26 22:33 UTC
The downloaded content is failed to be played again after you exit the channel page
![kolibri_playback](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/93b7043f-bd4f-4433-858d-67f174565f83)

Reproduce steps:
1. Go into a channel and select a content to download
2. After the download completes, play the content
3. Exit the channel then go into the channel again and play the content

Actual Result:
- In Step 2: the content can be played as expected.
- In Step 3: It shows an error message as: "Kolibri is unable to render this resource"
- This issue can be reproduced in both Windows and Android platforms

Logs:
- Windows log:
[kolibri.txt](https://github.com/endlessm/kolibri-explore-plugin/files/11875259/kolibri.txt)

**Comment by manuq** [comment] 2023-06-28 12:59
Thanks for reporting @vanessa-chang ! This is yet another caching issue: #687

**Comment by vanessa-chang** [comment] 2023-07-11 13:37
Test the latest package: Ladybird 6.26-365

"Kolibri is unable to render this resource" error is shown when downloading the 2nd source within the same channel.
Only the first content can be played.

Test steps:
1. Go into a channel and download a content
2. Play the content
3. Download a 2nd content within the same channel
4. Play the content

Result:
The error will be shown in step 4

**Comment by erikos** [comment] 2023-07-12 08:51
Trying to reproduce this  - the first thing I have seen is that, after I played back the video the first time and closing the channel and opening it again, the card still only shows the _checkmark-for-download-complete_ - but no _watch_ button. This seems to be related to that issue of updates not happening. I have not seen the playback issue so far. But one case where the _watch_ button in the detail page was grayed out but the video was still playable.

**Comment by dbnicholson** [comment] 2023-07-12 22:58
Since #687 was resolved, I think we'll need to sprinkle in some more `force = true` with `fetch*` or `clearCache()` in certain scenarios. Even though the HTTP cache issues have been resolved, there's still an in-memory JS cache for each `Model` and `Collection`. I imagine if you reload the page, it works.

**Comment by vanessa-chang** [comment] 2023-07-25 10:14
This issue cannot be reproduced in Ladybird 6.30-374

**Comment by erikos** [comment] 2023-07-31 10:03
> This issue cannot be reproduced in Ladybird 6.30-374

Great, let's close this then.

**Closed by erikos** 2023-07-31 10:03 UTC
Labels: bug
