### ISSUE TITLE
User Testing: switch online/offline

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#595] opened 2023-06-13 12:43 UTC
https://github.com/endlessm/kolibri-explore-plugin/issues/572

On (default): show all content
Off: show only dowloaded

On: show only downloaded
Off (defaults): show all content

**Comment by manuq** [comment] 2023-06-14 20:21
Is this a duplicate of #572 ?

**Comment by wjt** [comment] 2023-08-11 15:54
I think this is actually a duplicate of :

- [ ] https://github.com/endlessm/kolibri-explore-plugin/issues/596

so I am closing it as such.

**Closed by wjt** 2023-08-11 15:54 UTC
