### ISSUE TITLE
Android & Windows apps do not start since build system rework

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#703] opened 2023-07-14 14:36 UTC
![Screenshot 2023-07-14 16 26 04](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/06e6dae8-9182-4b42-809d-aee118727f9b)

Version should be Ladybird 6.27-366 - though the Play console shows:
![Screenshot from 2023-07-14 16-33-13](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/8adcc4c9-e571-4e7a-8f92-9f6e84ab7d24)

**Comment by dylanmccall** [comment] 2023-07-14 18:58
It looks like this regressed in https://github.com/endlessm/kolibri-explore-plugin/pull/662: our builds no longer include `kolibri_explore_plugin/build/kolibri_explore_plugin.app_stats.json`.

**Comment by dylanmccall** [comment] 2023-07-14 20:27
Oh oops, except we probably don't want to actually close this yet until we've verified it :)

**Comment by erikos** [comment] 2023-07-15 10:10
Kicked of a new release of the explore plugin https://github.com/endlessm/kolibri-explore-plugin/actions/runs/5561682701

**Comment by wjt** [comment] 2023-07-17 12:15
The app now sits forever at the Kolibri bird animation.

I connected to the server from a regular web browser and looked at the web console:

```
GET http://192.168.4.43:42819/static/kolibri_explore_plugin.app/kolibri_explore_plugin.app6.28.0.css net::ERR_ABORTED 404 (Not Found)
GET http://192.168.4.43:42819/static/kolibri_explore_plugin.app/kolibri_explore_plugin.app-6.28.0.js net::ERR_ABORTED 404 (Not Found)
```

I think this is likely to be the problem.

**Comment by wjt** [comment] 2023-07-17 12:16
(Those filenames look suspicious to me.)

**Comment by wjt** [comment] 2023-07-17 12:17
I see the same inspecting the app's “Kolibri” webview via `chrome://inspect#devices`.

**Comment by wjt** [comment] 2023-07-18 08:45
I think the problem is that the wheel used to include the compiled Javascript & CSS (but no source) and now it includes the source (but no compiled assets).

This would explain why the compiled JS and CSS is failing to load :-)

Before:
![Screenshot from 2023-07-18 09-42-24](https://github.com/endlessm/kolibri-explore-plugin/assets/86760/e15b9b98-2337-49db-b896-70e6519812a5)

After (notice that the `kolibri_explore_plugin.app` directory is completely missing):

![Screenshot from 2023-07-18 09-42-26](https://github.com/endlessm/kolibri-explore-plugin/assets/86760/ac4a21d1-5133-45fa-af11-17d43526f083)

**Comment by pwithnall** [comment] 2023-07-18 13:01
I think this is far as I can get without some guidance from someone who actually knows how this towering pile of build system is supposed to work.

**Comment by wjt** [comment] 2023-07-18 13:04
@dylanmccall @dbnicholson Please could you take a look?

**Comment by dbnicholson** [comment] 2023-07-18 15:21
Sure, I can take a look.

**Comment by dbnicholson** [comment] 2023-07-18 15:44
> From some poking around on my system, it appears that `yarn build` creates the `kolibri_explore_plugin.app` files in my pyenv deployment, rather than in the source directory. I think the Python dist tooling is looking for them in the source directory (once #706 is applied).
> 
> On my system, `kolibri_explore_plugin.app` is being created in `~/.local/bin/pyenv.git/versions/kolibri-py3.9/lib/python3.11/site-packages/kolibri_explore_plugin/static/kolibri_explore_plugin.app/`. It includes the various CSS/etc. files listed above, with what look like the right version numbers.

It took me a while to reproduce this, but you must have kolibri-explore-plugin installed in your virtualenv or pyenv. Can you run `pip list | grep kolibri-explore-plugin`? With the plugin not installed or installed editable (`pip install --editable .`), the yarn build compiled the assets in the source tree. With a regular installed plugin (`pip install kolibri-explore-plugin`), it did compile the assets into the installed location in `site-packages`.

I didn't look closely at your proposed PR, but I think in general `kolibri-tools` should add the local plugin path to the beginning of the python path rather than appending to ensure it doesn't find an installed version of the plugin.

That said, our build process doesn't ever attempt to install the plugin, so just merging #706 should be enough.

**Closed** 2023-07-18 18:07 UTC
Labels: bug

**Comment by pwithnall** [comment] 2023-07-19 12:19
> It took me a while to reproduce this, but you must have kolibri-explore-plugin installed in your virtualenv or pyenv. Can you run `pip list | grep kolibri-explore-plugin`? With the plugin not installed or installed editable (`pip install --editable .`), the yarn build compiled the assets in the source tree. With a regular installed plugin (`pip install kolibri-explore-plugin`), it did compile the assets into the installed location in `site-packages`.

Yes, kolibri-explore-plugin is installed in my pyenv. I thought I had only installed it editable, but perhaps I installed it normally at some point as well.

> I didn't look closely at your proposed PR, but I think in general `kolibri-tools` should add the local plugin path to the beginning of the python path rather than appending to ensure it doesn't find an installed version of the plugin.

I’ve submitted that patch upstream then: https://github.com/learningequality/kolibri/pull/10994
