### ISSUE TITLE
The channel descriptions in the discovery page is only shown when the app is launched

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#799] opened 2023-09-12 10:04 UTC
Test package: https://github.com/endlessm/endless-key-flatpak/actions/runs/6153210584 & Manatee 6.44-397

Each time you launch the app, you can see the channel description is there under the title in each card. (except for the feature channels)
However, if you reload the app, swtich to different tab and return to the discovery page or get into any channel then exit back to the discovery page, the desciption will be disappeared.

[Screen recording 2023-09-12 5.01.59 PM.webm](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/62a9a280-8a1e-4014-98d0-1a45f74bb0e0)

**Comment by dbnicholson** [comment] 2023-09-12 22:19
Notice that it's replaced the subtitle (e.g., "Scuba Jack presents China.") with the channel icon (e.g., "Virtual Field Trips"). I don't know what's supposed to be the right thing, but this looks like a similar issue to #780.

I'm pretty sure it's supposed to show the channel icon since it tries to [add the channel to the node](https://github.com/endlessm/kolibri-explore-plugin/blob/master/kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue#L136). The card decides whether to show the channel icon or the subtitle based on whether the [`node.channel` property is truthy](https://github.com/endlessm/kolibri-explore-plugin/blob/master/packages/ek-components/src/components/EkCardBody.vue#L60). However, `rootNodes` is not necessarily populated when the page first loads, so `addChannelToNode` returns `undefined`.

Someone with a better understanding of the data model needs to figure out how to make this work synchronously with `rootNodes`.

**Comment by dbnicholson** [comment] 2023-09-15 17:14
@jprvita could you have a look at this? I believe the fix is one of:

* Make this synchronized with `rootNodes` being populated somehow.
* Do something like 424de8730eb3a7e72c961c0e838f927de2be4e71 where you get the channel data from `ChannelResource` and manually set it as `node.channel` rather than looking it up in `rootNodes`.

**Comment by erikos** [comment] 2023-09-25 16:27
Just reproduced the issue that this can come and go in the current version of the Flatpak. I started the app and the description was there in the cards on the Discovery page. Then I opened a channel and closed it - description is gone. Closed the app and started again - description is there - opening closing a channel - description is gone.

**Comment by manuq** [comment] 2023-09-25 18:53
After some digging: the cards in the page should always look the same:
- Without a description
- With the channel icon and title above the content title

But something regressed and when the app loads from the root URL (first launch) it is wrongly displayed (with description, without channel information).

**Comment by dbnicholson** [comment] 2023-09-25 21:18
As described above, it's because it expects to get the data from `rootNodes`, but there's no synchronization to ensure `rootNodes` is populated. Normally `rootNodes` wins that race, but it's less likely when the app is first launched and lots of models are being populated for the first time.

If you know how to make it synchronous, that would be great. Otherwise I would just have that code gather the channel data on its own and duplicate whatever mutations are supposed to happen.

**Comment by manuq** [comment] 2023-09-26 11:33
> If you know how to make it synchronous, that would be great. Otherwise I would just have that code gather the channel data on its own and duplicate whatever mutations are supposed to happen.

No need to be synchronous. The page is reactive to the [`core.loading` state](https://github.com/endlessm/kolibri-explore-plugin/blob/910e8b3e108ba8f7a3ed9e4a12cda557615ed1d2/kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue#L109), and does the fetch after loading the rootNodes https://github.com/endlessm/kolibri-explore-plugin/blob/910e8b3e108ba8f7a3ed9e4a12cda557615ed1d2/kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue#L112-L123 . I am revisiting the handlers logic (whch set the loading state) to see why it regressed.

**Comment by manuq** [comment] 2023-09-26 12:23
Found it! I introduced this while rewiring the Welcome. Fix: https://github.com/endlessm/kolibri-explore-plugin/pull/852

**Comment by erikos** [comment] 2023-09-27 08:16
The expected behavior here is that we would never see a description on the cards in the Discovery page, correct?

**Comment by vanessa-chang** [comment] 2023-09-27 10:31
Verified with the latest flatpack v0.7 plugin v7.3.0

This issue can be seen only when the user completes the download and enter to the Discovery page for the first time.
It will no longer be reproduced after that.

**Comment by erikos** [comment] 2023-09-27 13:43
Nearly there - as Vanessa is saying. The very first time right after the content pack download, the cards have a description in the Discovery page. All the times afterwards - they do not.

**Comment by manuq** [comment] 2023-09-28 11:58
Great spotting @vanessa-chang and @erikos! Ready for review. Unfortunately all this routing is very fragile.

**Comment by erikos** [comment] 2023-09-29 07:30
https://github.com/endlessm/kolibri-explore-plugin/pull/860 has been merged.

**Closed by erikos** 2023-09-29 07:30 UTC
Labels: bug

**Comment by vanessa-chang** [comment] 2023-10-02 08:02
Verified passed in flatpak v0.7 with plugin v.7.5.0
